name: Publish
on:
    push:
        branches:
            - main

permissions: write-all

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Begin...
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install dependencies
              run: cd packages && npm install

            - name: Build
              run: cd packages && npm run build

            - name: Version Bump
              uses: "phips28/gh-action-bump-version@master"
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  PACKAGEJSON_DIR: "packages"

            - name: Publish to npm
              run: cd packages && echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc && npm publish --access public
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
